In [1]:
from pathlib import Path
import pandas as pd

In [2]:
file = "C:/Github/VGP/data/Events2023-08-28T14_09_07.csv"

data = pd.read_csv(Path(file))

In [3]:
data

,Item1,Item2.Item1.Item1,Item2.Item1.Item2.Value.IsInvalid,Item2.Item1.Item2.Value.ElementType,Item2.Item1.Item2.Value.Size.Width,Item2.Item1.Item2.Value.Size.Height,Item2.Item1.Item2.Value.Rows,Item2.Item1.Item2.Value.Cols,Item2.Item1.Item2.Value.Step,Item2.Item1.Item2.Value.Depth,Item2.Item1.Item2.Value.Channels,Item2.Item1.Item2.Value.ElementSize,Item2.Item1.Item2.Value.Data,Item2.Item1.Item2.Value.IsClosed,Item2.Item1.Item2.Timestamp,Item2.Item2
0,pump2_on,True,False,6,10,3,3,10,80,F64,1,8,622893840,False,2023-08-28T14:09:26.3487360+02:00,145
1,pump2_off,True,False,6,10,3,3,10,80,F64,1,8,13059248,False,2023-08-28T14:09:28.3449472+02:00,165
2,Lick2,True,False,6,10,3,3,10,80,F64,1,8,624571504,False,2023-08-28T14:09:28.6473856+02:00,168
3,Lick2,True,False,6,10,3,3,10,80,F64,1,8,624072144,False,2023-08-28T14:09:28.9508480+02:00,171
4,Lick2,True,False,6,10,3,3,10,80,F64,1,8,623844528,False,2023-08-28T14:09:29.2433792+02:00,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1055,Lick1,True,False,6,10,3,3,10,80,F64,1,8,622124736,False,2023-08-28T14:29:00.2419712+02:00,11879
1056,Lick1,True,False,6,10,3,3,10,80,F64,1,8,623290112,False,2023-08-28T14:29:04.8475520+02:00,11925
1057,Lick1,True,False,6,10,3,3,10,80,F64,1,8,618478384,False,2023-08-28T14:29:05.0391040+02:00,11927
1058,Lick1,True,False,6,10,3,3,10,80,F64,1,8,622125344,False,2023-08-28T14:29:05.2396544+02:00,11929
1059,Lick1,True,False,6,10,3,3,10,80,F64,1,8,618472000,False,2023-08-28T14:29:06.4478976+02:00,11941

In [4]:
event_rows = []
for row in data.iterrows():
    event = row[1][0]
    if event == "pump1_on" or event == "pump2_on":
        try:
            #write current data, if none then skip
            event_rows.append([current_event, current_start_frame, nlicks1, nlicks2])
        except:
            pass
        
        current_event = event
        current_start_frame = row[1][15]
        nlicks1 = 0
        nlicks2 = 0
    elif event == "Lick1":
        nlicks1 += 1
    elif event == "Lick2":
        nlicks2 += 1

In [21]:
cols = ["event", "start_frame", "nlicks1", "nlicks2"]

df = pd.DataFrame(event_rows, columns=cols)

In [29]:
def make_loaded_column(df, event, lickscol):
    loaded = False
    newcol = []
    for row in df.iterrows():
        newcol.append(loaded)
        if row[1][0] == event and row[1][lickscol] == 0:
            loaded = True
        elif row[1][lickscol] > 0:
            loaded = False
    return newcol

df['spout1_loaded'] = make_loaded_column(df, 'pump1_on', 2)
df['spout2_loaded'] = make_loaded_column(df, 'pump2_on', 3)

In [30]:
df

,event,start_frame,nlicks1,nlicks2,loaded 1,spout1_loaded,spout2_loaded
0,pump2_on,145,1,7,False,False,False
1,pump1_on,437,35,42,False,False,False
2,pump1_on,689,3,9,False,False,False
3,pump2_on,923,0,2,False,False,False
4,pump2_on,1215,14,0,False,False,False
5,pump1_on,1436,30,11,False,False,True
6,pump1_on,1667,4,2,False,False,False
7,pump1_on,1864,2,0,False,False,False
8,pump1_on,2037,20,4,False,False,False
9,pump1_on,2338,17,4,False,False,False
10,pump2_on,2517,5,3,False,False,False
11,pump1_on,2689,18,1,False,False,False
12,pump2_on,2935,25,7,False,False,False
13,pump2_on,3164,10,11,False,False,False
14,pump1_on,3476,1,0,False,False,False
15,pump1_on,3681,10,0,False,False,False
16,pump1_on,3897,14,7,False,False,False
17,pump1_on,4129,6,5,False,False,False
18,pump1_on,4302,0,3,False,False,False
19,pump1_on,4516,0,0,True,True,False
20,pump1_on,4768,0,0,True,True,False
21,pump2_on,4946,4,1,True,True,False
22,pump1_on,5223,4,0,False,False,False
23,pump2_on,5450,1,0,False,False,False
24,pump1_on,5702,6,0,False,False,True
25,pump2_on,6019,6,0,False,False,True
26,pump2_on,6233,1,0,False,False,True
27,pump1_on,6413,8,0,False,False,True
28,pump1_on,6605,35,0,False,False,True
29,pump1_on,6904,22,0,False,False,True
30,pump1_on,7147,13,0,False,False,True
31,pump1_on,7351,24,32,False,False,True
32,pump2_on,7558,9,15,False,False,False
33,pump2_on,7872,20,2,False,False,False
34,pump2_on,8093,18,5,False,False,False
35,pump2_on,8408,13,8,False,False,False
36,pump1_on,8621,21,5,False,False,False
37,pump1_on,8808,26,14,False,False,False
38,pump1_on,9032,12,4,False,False,False
39,pump2_on,9329,6,7,False,False,False
40,pump2_on,9609,16,9,False,False,False
41,pump1_on,9862,28,16,False,False,False
42,pump1_on,10071,26,11,False,False,False
43,pump1_on,10317,30,2,False,False,False
44,pump2_on,10577,31,0,False,False,False
45,pump1_on,10856,32,23,False,False,True
46,pump1_on,11141,9,3,False,False,False
47,pump2_on,11344,3,1,False,False,False
48,pump1_on,11618,15,12,False,False,False